/**
 * Resolves sample-tokens.json into CSS custom properties + an inventory for the
 * reference section of the landing page.
 *
 * The semantic layers (bg/text/border/icon) store their $value as a Figma
 * VARIABLE_ALIAS -- `{ id: "VariableID:75:117", type: "VARIABLE_ALIAS" }` -- and
 * the export does not carry the table those ids point at. The ids form one
 * contiguous run, 75:117 through 75:159, which is exactly 43 slots, and
 * `primitive.*` holds exactly 43 colors. ALIAS_RAMP_ORDER below reconstructs
 * that run; see docs/index.html "How the aliases were resolved" for the
 * evidence, and `npm run check` for the assertions that keep it honest.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const OUT = join(ROOT, "docs");

const ALIAS_START = 117;
const ALIAS_RAMP_ORDER = [
  ["neutral", ["100", "200", "300", "350", "400", "500", "600", "700", "800", "900", "black", "white"]],
  ["brown", ["50", "100", "200", "300", "400", "500", "600"]],
  ["amber", ["100", "200", "300", "400"]],
  ["blue", ["100", "200", "300", "400", "500", "600"]],
  ["green", ["100", "200", "300", "400"]],
  ["red", ["100", "200", "300", "400"]],
  ["yellow", ["100", "200", "300", "400", "500", "600"]],
];

const tokens = JSON.parse(readFileSync(join(ROOT, "sample-tokens.json"), "utf8"));

/** Every leaf token in the file, in document order. */
function* walk(node, path = []) {
  if (node && typeof node === "object") {
    if ("$type" in node && "$value" in node) {
      yield { path, token: node };
      return;
    }
    for (const [key, value] of Object.entries(node)) yield* walk(value, [...path, key]);
  }
}

/** `borderRadius.lg` -> `--border-radius-lg`; purely mechanical, no hand-written aliases. */
const cssVarName = (path) =>
  "--" + path.map((p) => p.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase()).join("-");

// --- Rebuild the alias id -> primitive lookup ------------------------------
const aliasTable = new Map();
let slot = ALIAS_START;
for (const [family, shades] of ALIAS_RAMP_ORDER) {
  for (const shade of shades) {
    const value = tokens.primitive?.[family]?.[shade]?.$value;
    if (typeof value !== "string") throw new Error(`primitive.${family}.${shade} missing from tokens`);
    aliasTable.set(`VariableID:75:${slot}`, { path: ["primitive", family, shade], value });
    slot++;
  }
}
if (slot - ALIAS_START !== 43) throw new Error(`ramp order covers ${slot - ALIAS_START} slots, expected 43`);

// --- Flatten -------------------------------------------------------------
const inventory = [];
for (const { path, token } of walk(tokens)) {
  const raw = token.$value;
  const entry = {
    path: path.join("."),
    group: path[0],
    name: path.slice(1).join("."),
    cssVar: cssVarName(path),
    type: token.$type,
    description: token.$description ?? null,
    alias: null,
  };

  if (raw && typeof raw === "object" && raw.type === "VARIABLE_ALIAS") {
    const target = aliasTable.get(raw.id);
    if (!target) throw new Error(`unresolved alias ${raw.id} at ${entry.path}`);
    entry.alias = { id: raw.id, target: target.path.join(".") };
    entry.value = target.value;
    entry.css = target.value;
  } else if (token.$type === "number") {
    entry.value = raw;
    entry.css = `${raw}px`;
  } else {
    entry.value = raw;
    entry.css = raw;
  }
  inventory.push(entry);
}

// Root-level ramps duplicate primitive.* but every value exported as #ffffff.
const primitiveHex = new Map(
  inventory.filter((t) => t.group === "primitive").map((t) => [t.path.replace("primitive.", ""), t.value]),
);
for (const entry of inventory) {
  if (entry.alias || entry.group === "primitive") continue;
  if (entry.type !== "color" || entry.value !== "#ffffff") continue;
  if (primitiveHex.has(entry.path)) entry.placeholder = primitiveHex.get(entry.path);
}

// --- Emit ----------------------------------------------------------------
mkdirSync(OUT, { recursive: true });

const byGroup = inventory.reduce((acc, t) => ((acc[t.group] ??= []).push(t), acc), {});
const css = [
  "/* Generated by build.mjs from sample-tokens.json -- do not edit by hand. */",
  ":root {",
  ...Object.entries(byGroup).flatMap(([group, entries]) => [
    `  /* ${group} (${entries.length}) */`,
    ...entries.map((t) => {
      const note = t.alias ? `  /* ${t.alias.id} -> ${t.alias.target} */` : "";
      return `  ${t.cssVar}: ${t.css};${note}`;
    }),
    "",
  ]),
  "}",
  "",
].join("\n");

writeFileSync(join(OUT, "tokens.css"), css);
writeFileSync(
  join(OUT, "token-data.js"),
  "/* Generated by build.mjs from sample-tokens.json -- do not edit by hand. */\n" +
    `window.TOKENS = ${JSON.stringify(inventory, null, 2)};\n`,
);

const aliased = inventory.filter((t) => t.alias).length;
const usedSlots = new Set(inventory.filter((t) => t.alias).map((t) => t.alias.id)).size;
console.log(
  `tokens: ${inventory.length}  (${aliased} alias-backed, ${inventory.length - aliased} literal)\n` +
    `alias slots referenced: ${usedSlots}/43\n` +
    `groups: ${Object.entries(byGroup).map(([g, e]) => `${g}=${e.length}`).join(" ")}\n` +
    `wrote docs/tokens.css, docs/token-data.js`,
);
