/* Renders the token reference from token-data.js (generated by build.mjs).
   Nothing here is hand-listed: if a token exists in sample-tokens.json it
   appears below, painted by its own custom property. */
(function () {
  "use strict";

  var tokens = window.TOKENS || [];

  var RAMP_GROUPS = ["primitive", "neutral", "brown", "amber", "blue", "green", "red", "yellow"];
  var ORDER = ["bg", "text", "icon", "border", "colors", "spacing", "borderRadius", "primitive"];
  var BLURB = {
    bg: "Surface fills, every one an alias onto a primitive.",
    text: "Type colours, including the states a design file usually forgets.",
    icon: "Icon colours; mirrors the text ramp so glyphs and copy stay in step.",
    border: "Strokes and dividers.",
    colors: "A second, self-contained palette with literal hex values. Shares nothing with the alias layer.",
    spacing: "The spacing scale, in px.",
    borderRadius: "The corner radius scale, in px.",
    primitive: "The raw ramps every alias above resolves to.",
  };

  /* Ramp steps paint their own background, so the label needs a readable
     foreground. Both candidates are themselves tokens. */
  function readableOn(hex) {
    var m = /^#([0-9a-f]{6})$/i.exec(hex || "");
    if (!m) return "var(--primitive-neutral-900)";
    var n = parseInt(m[1], 16);
    var c = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map(function (v) {
      v /= 255;
      return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
    });
    var lum = 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
    return lum > 0.42 ? "var(--primitive-neutral-900)" : "var(--primitive-neutral-white)";
  }

  function el(tag, className, text) {
    var node = document.createElement(tag);
    if (className) node.className = className;
    if (text != null) node.textContent = text;
    return node;
  }

  // --- Summary ------------------------------------------------------------
  var aliased = tokens.filter(function (t) { return t.alias; });
  var placeholders = tokens.filter(function (t) { return t.placeholder; });
  var slots = {};
  aliased.forEach(function (t) { slots[t.alias.id] = true; });
  var groups = tokens.reduce(function (acc, t) {
    (acc[t.group] = acc[t.group] || []).push(t);
    return acc;
  }, {});

  var stats = [
    [tokens.length, "tokens in the file"],
    [aliased.length, "resolved through aliases"],
    [Object.keys(slots).length + "/43", "alias slots referenced"],
    [Object.keys(groups).length, "collections"],
    [placeholders.length, "exported as #ffffff"],
  ];
  var statRow = document.getElementById("stats");
  stats.forEach(function (s) {
    var box = el("div", "stat");
    box.appendChild(el("b", null, String(s[0])));
    box.appendChild(el("span", null, s[1]));
    statRow.appendChild(box);
  });

  // --- Group rendering ----------------------------------------------------
  function swatch(t) {
    var row = el("div", "swatch");

    var chip = el("span", "swatch-chip");
    if (t.type === "number") {
      chip.className += " is-number";
      chip.textContent = t.value;
    } else {
      chip.style.background = "var(" + t.cssVar + ")";
    }
    row.appendChild(chip);

    var body = el("div", "swatch-body");
    body.appendChild(el("div", "swatch-name", t.path));

    var meta = el("div", "swatch-meta", t.type === "number" ? t.value + "px" : t.value);
    body.appendChild(meta);

    if (t.alias) {
      body.appendChild(el("div", "swatch-meta swatch-alias", "↳ " + t.alias.target));
    }
    if (t.description) {
      body.appendChild(el("div", "swatch-meta", t.description));
    }
    if (t.placeholder) {
      body.appendChild(el("span", "swatch-flag", "placeholder — expected " + t.placeholder));
    }
    row.appendChild(body);
    return row;
  }

  function rampBlock(label, entries) {
    var wrap = el("div", "ramp");
    wrap.appendChild(el("div", "ramp-label", label));
    var steps = el("div", "ramp-steps");
    entries.forEach(function (t) {
      var step = el("div", "ramp-step");
      step.style.background = "var(" + t.cssVar + ")";
      step.style.color = readableOn(t.value);
      step.appendChild(el("span", null, t.path.split(".").pop()));
      step.appendChild(el("span", null, t.value));
      steps.appendChild(step);
    });
    wrap.appendChild(steps);
    return wrap;
  }

  function renderGroup(name, entries) {
    var section = el("section", "group");

    var head = el("div", "group-head");
    head.appendChild(el("h3", null, name));
    head.appendChild(el("span", "count", String(entries.length)));
    if (BLURB[name]) head.appendChild(el("p", null, BLURB[name]));
    section.appendChild(head);

    if (RAMP_GROUPS.indexOf(name) !== -1) {
      // Group by ramp family: `primitive.blue.400` -> "blue"; `blue.400` -> "blue".
      var families = [];
      var byFamily = {};
      entries.forEach(function (t) {
        var parts = t.path.split(".");
        var family = parts.length > 2 ? parts[1] : parts[0];
        if (!byFamily[family]) { byFamily[family] = []; families.push(family); }
        byFamily[family].push(t);
      });
      families.forEach(function (f) {
        section.appendChild(rampBlock(name === "primitive" ? "primitive." + f : f, byFamily[f]));
      });
    } else {
      var grid = el("div", "swatch-grid");
      entries.forEach(function (t) { grid.appendChild(swatch(t)); });
      section.appendChild(grid);
    }
    return section;
  }

  var host = document.getElementById("groups");
  var seen = {};
  ORDER.forEach(function (name) {
    if (!groups[name]) return;
    seen[name] = true;
    host.appendChild(renderGroup(name, groups[name]));
  });

  // The seven root-level ramps duplicate primitive.* but exported as #ffffff.
  var leftovers = Object.keys(groups).filter(function (g) { return !seen[g]; });
  if (leftovers.length) {
    var flat = [];
    leftovers.forEach(function (g) { flat = flat.concat(groups[g]); });
    var section = renderGroup("unresolved root ramps", flat);
    section.querySelector(".group-head").appendChild(
      el("p", null, leftovers.join(", ") + " — every value exported as #ffffff"),
    );
    host.appendChild(section);
  }

  document.getElementById("footnote").textContent =
    tokens.length +
    " tokens rendered from sample-tokens.json. " +
    aliased.length +
    " resolve through the reconstructed alias table; " +
    placeholders.length +
    " root-ramp values came out of the export as #ffffff and are shown as-is.";
})();
